language: node_js
node_js: '11'
dist: xenial
# When pushing a tagged commit, Travis adds two builds: one with the tag, one
# without. We only want to build the one with the tag, because it's the one
# that runs the deployment stage
if: '!(commit_message =~ /^Release/ && tag is blank)'
jobs:
  include:
    # Test on Windows/Mac/Linux using latest Node.js.
    # Also test on Linux with older Node.js versions.
    # We do not run each possible combination to make CI faster.
    - os: windows
    - os: osx
    - node_js: '8.10.0'
    - node_js: '11'
    # Test coverage check must happen after tests for the whole matrix have
    # been performed, so we get the merged coverage map
    - stage: Coverage check
      # If this fails during a PR, CI will fail. However when CI fails, codecov
      # does not post any comment. Since codecov comments are nicer than
      # Travis Buddy comments for this, we skip it during PRs. Also this makes
      # PRs checks faster.
      if: type != pull_request
      script: gulp coverage
    # Deployment must happen after tests for the whole matrix have been
    # performed, so we use `jobs.include` with a different `stage`.
    - stage: Deploy
      if: type != pull_request && tag is not blank
      script: gulp publish
      # NPM_TOKEN environment variable
      env:
        secure: 'OaYc3pHR/3ZEF8h8OduKMoAvcscF3Wgbo9XdIjs+Uu2zWVXqmgjavsZsBlRReSbfoYvRwmDMPmtIeafAKNOnbXKNEuEIXUSoHndqRZdaCmmc17jQZt85y5KyoMeyspk+sEuj92FqDIo84fbSvLyRKtos7ggqMzYzAgZyktmf0IXWjWHsc0vXh1F3oRwWuVxuycr7qUnrJYZDOXVmEnvbcNzkJjaA0tcVAHaqdpDMcGm/Jp/jqIv4ZeR4o26iAr1zfLk5lUxBOqDocw5+4OIbCk3tCQl7B6i/zHd1IATf0sTMkMWI/iPw5z7/eEWhXwgUQtjb5yfehMw0NRVhaohOkD8T0zlUSda1T7LkERBl4FHwIRtEHEkK8DbyuQ5xrrtP2Od+679QkkDNkaDtnTQvRq7UtutiPi/NherkVwfepLirKCzArwKmIN7OfHFdWUZCNQ02QgEcqISOlpuBZS1sjRX6aDNI8GC5PMHx9P2HrBVmXumR/f32/KFxGHRifana5lf7f0gn3Zw+AldO1UGSqkW5z7+syg82FLYkVCH+0A+ISS9vLfbPgD1bogjvgnSESPFK/0IMMud+3OJVEVmba6ocDtUt2G97GHAhP/uz46OsQw85hxlE/N6YSI6ETPyXIU5dV5xnYv3MYr4lioTIyXMNt+2Z7dLFctP3fHOEiag='
notifications:
  webhooks:
    - https://www.travisbuddy.com?only=failed,errored&insertMode=update
  email: false
# We do not use `cache: npm` because downloading and uploading the cache
# actually takes more time than it saves during `npm ci`.
