language: node_js
node_js:
  - 6.5.0
  - 8
  - 10
  - 11
os:
  - windows
  - osx
  - linux
dist: xenial
script: npm test
# When pushing a tagged commit, Travis adds two builds: one with the tag, one
# without. We only want to build the one with the tag, because it's the one
# that runs the deployment stage
if: '!(commit_message =~ /^Release/ && tag is blank)'
jobs:
  include:
    # Test coverage check must happen after tests for the whole matrix have
    # been performed, so we get the merged coverage map
    - stage: Coverage check
      os: linux
      node_js: 11
      script: npm run check-coverage
      # If CI fails, codecov does not post a bot comment on PR, so we skip it
      if: type != pull_request && (branch == master || tag is not blank)
    # Deployment must happen after tests for the whole matrix have been
    # performed, so we use `jobs.include` with a different `stage`
    - stage: Deploy
      os: linux
      node_js: 11
      # We have already run tests
      script: npm run build
      if: tag is not blank
      # We run `release-it` locally (which tagged the commit and create a
      # GitHub release) but we publish to npm only after CI success.
      deploy:
        provider: npm
        email:
          secure: QSzgqdIXSi5BT4CQdB30TE91C8DiZBN/0mNT0b2bIjjSV0STLHTabBhv0MyrtePToIGTqIijfZ2QVr2iJ1qm8u5jYKFiMXBETi5nIf2lt82okR7gtvRU1Fg12AsybaDYuyoUDJwCY0CaDmtkDWPBFMwF8fLVhofbgOJN9sDkswaZKWIG+8xj7gGcO2pMYcDdMimiFvEDMxe7cnk2wy08DOcSD1zn/gttRKTojZMWoGieVw1nNzlKG1rDlp+D1L5fgBw1TF+x76TuWa6ntPXc2DgNQc1bgV+66wq1TEHDhu2eTdjP1PPo/o0At28cBOiPYBxFXxGyuVtlO76+2N7QduoQJRpjKUuSmR/L3zU+fl0IEkKG9UL4K+mPGpMXsb51YLzlPmigGij3OaOnZIetJBRR5AX3X6scFlArtU4FZCoX7ZW+6J2NoTt8ayz/9DM/9aKLfbes2sY/RNwyyKrnpmMHRkv7aWSSvC8T+86Q1xSXfcLI8/lgubkhzjwn/WLyOcDqEUST1Q7UR7IjnDMuYfGxfZLtzQeSpaKkU5IzYsHpD1LPM/eRksZ4NmF403ya8XvtynC3NiSxMw6mLMmCLZoU62cpsoaHL/svt2lO0dhdI2HP9j9afSFEjruLwMgbc/cScgsjziJeS6emyJUr8Cd5Q++/RdTnUV3qen0UoW4=
        api_key:
          secure: tvS2dzSBIOhMv97l9qnXlcytJ7+mYc2xO7iOskKBhDZ7jcEKGNos85eZTSAcYykPav90z5g75apBAM2LaJxbMeEA7ZzFWOtgQOqbgvcEMIrOKg83CPToI1Yu+5y4sAa1SYCe30max3aay9Zbu8ywF9uyH5zIt5MMmDPnuw3eM64qATlHf76xlbsxwI8bNCNnVbjd8a4RJt1ACDpUs0cTUSfU6YYb1r3Iavig6KCvPDHAlAbCuVndedMD8AkSu9tQ84FGpq5Yc3b1/akSHZtAeyATD8okVm9OJrtOWUXC7qJGJR2urMZ31Uy9qEQ5uQMU0Ry3qdCqm9tiVyOrPrhWoP1Js0mtYSJfsiHzykdWtLdODdhFHQKjKWccx+D4+Rb3TzPMEhZGYi9DalgOX5GhpHoFSUygwyUas+iKeAhsV/hq233pb/Vn+ypaJvxrCS0ZCK2QP1YoCdmYLzgCGjjPSR+V9v+FTDUE4FpOcUwvsy+syoLPJlGBRmEgc2wHYIL+f2KMx5qV43EAvNgm0oBSV+sYPtntacyi/XYihVlWQQaqnsn9DTfHtrMUMLYeZZDBTtPm+QnNSbdhOTHfxKDlTBnGGhuiDP1GobnzSqfHphBMp/+eRJJJG60RIjNmQ3gR1LD0VnZEkudn2Fh75ayr+EJIaC8trr/tA/htxNQiODE=
        on:
          tags: true
        # We want to run install step and keep built files for release
        skip_cleanup: true
cache: npm
notifications:
  webhooks:
    - https://www.travisbuddy.com?only=failed,errored&insertMode=update
  email: false
